DEVICE          : cuda #cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : /censipam_data/eliasqueiroga/app_novo/temp_WHOLE         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : UNet          #SFNet, DDRNet                                           # name of the model you are using, SegFormer SFNet|ResNetD-18
  BACKBONE      :               # ResNetD-18                                                 # model variant, MiT-B2
  PRETRAINED    :               # backbone model's weight 

DATASET:
  NAME          : Censipam                                              # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : /censipam_data/renam/datasets/sentinel_ready/segm/train                           # dataset root path
  IGNORE_LABEL  : -1

TRAIN:
  IMAGE_SIZE    : [512, 512]      # training image size in (h, w)
  BATCH_SIZE    : 16             # batch size used to train
  EPOCHS        : 500             # number of epochs to train
  EVAL_INTERVAL : 2              # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : OhemCrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.001           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  


# 'output/DDRNet_None_Censipam.pth'
# 'output/SFNet_ResNetD-18_Censipam.pth'

EVAL:
  MODEL_PATH    : /censipam_data/eliasqueiroga/es_best_model_sd.pth  # trained model file path 'output/SFNet_ResNetD-18_Censipam.pth'
  IMAGE_SIZE    : [512, 512]                                                            # evaluation image size in (h, w)                       
  MSF: 
    ENABLE      : false                                                                 # multi-scale and flip evaluation  
    FLIP        : true                                                                  # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]                                     # scales used in MSF evaluation                


TEST:
  MODEL_PATH    : /censipam_data/eliasqueiroga/es_best_model_sd.pth  # trained model file path  output/DDRNet_None_Censipam.pth
  FILE          : /censipam_data/renam/netMerge/input/d3/masked.tif     
  LABEL         :                                                         # filename or foldername 
  IMAGE_SIZE    : [512, 512]                                                            # inference image size in (h, w)
  OVERLAY       : false                                                                  # save the overlay result (image_alpha+label_alpha)


#FILE          : '/censipam_data/renam/datasets/sentinel_model/test'          
#LABEL         : '/censipam_data/renam/datasets/sentinel_model/test_label'                                                         # filename or foldername 