
name          : unet
class         : UNet                                          
backbone      :                                      
checkpoint    : /censipam_data/eliasqueiroga/es_best_model_sd.pth

obj_list: ['background', 'deforestation']

device        : cpu   # cpu, cuda, cuda0, cuda1
batch_size    : 16     # amount of image to process at a time
patch_size    : 512   # used to filter prediction, default 0.5. Large value reduces false positive

threshold     : 0.45   # used to filter prediction, default 0.5. Large value reduces false positive